spring:
  kafka:
    bootstrap-servers: placeholder
    security:
      protocol: PLAINTEXT
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: com.nibado.example.datastores.kafka.ProductEventDeserializer
      auto-offset-reset: earliest
    producer:
      value-serializer: com.nibado.example.datastores.kafka.ProductEventSerializer
    listener:
      type: batch

service:
  topic: product-events